### ISSUE TITLE
Effects not firing in response to reactive list

### ISSUE THREAD

**Issue by meatballs** [anvilistas/reactive#22]
When using a `reactive_list`, I'm finding that using a simple assignment in an effect does not cause it to fire when the list changes (except for the first change). Instead, I have to do some operation on it.

e.g.
```
from anvil_reactive.main import reactive_list, effect


class ReactiveClass:
    signal = reactive_list()

    @effect
    def react_to_signal(self):
        _ = self.signal
        print("react_to_signal fired")

    @effect
    def react_to_signal_with_len(self):
        _ = len(self.signal)
        print("react_to_signal_with_len fired")


reactive_test = ReactiveClass()

reactive_test.signal.append(1)
reactive_test.signal.append(2)
```
gives
```
react_to_signal fired
react_to_signal_with_len fired
react_to_signal_with_len fired
```

Clone link for this example code: https://anvil.works/build#clone:3QI3BEYGOXNH2RGK=PINMJMBUL5U4O5NWS6CSAKDA

**Comment by meatballs** [comment]
Is this perhaps related to #5 and it's the `print` causing the problem?

In my real example, I have some logging occurring, which would have much the same effect.

**Comment by meatballs** [comment]
Fair enough! Here's the actual function:

```py
    @render_effect
    def refresh_tabulator(self):
        # I'm not sure why I need to use len here but it doesn't work
        # with just a simple assignment. There has to be some sort of
        # op on the signal in order for the function to fire.
        _signal = len(self.store.changelog)  # noqa unused_varaiable
        self.logger.debug("ReactivePersistenceTabulator: Refreshing tabulator")
        if not self.store or not self.store.view:
            self.logger.debug("ReactivePersistenceTabulator: Store is empty. Bailing out.")
            return
        if self.tabulator is None:
            self.logger.debug("ReactivePersistenceTabulator: No tabulator exists yet. Building it...")
            self.build_tabulator()
            return
        self.tabulator.deselect_row()
        self.tabulator.clear_app_table_cache()
        self.tabulator.set_data()
```

`self.store` is an instance of a class that has reactive attributes.

`store.view` is a data tables view - so it doesn't actually change. I just need a signal to tabulator to refresh and run the search on the view.

I suppose I could just a counter that I increment any time a relevant event occurs.

**Comment by s-cork** [comment]
yeah - so just appending doesn't change the list 
but reading the `len` of the list does cause the effect to re-run because the length changes anytime you append

An incrementing counter will do the same job
I think this is probably the correct behaviour
Are any of those other tabulator methods actually reading from the `changelog`?

**Comment by meatballs** [comment]
gotcha! No, nothing else is reading from there. It's purely signal.

**Comment by s-cork** [comment]
closing this issue for now
